# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd = {
      kernelModules = [];
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
    };
    loader = {
      systemd-boot.enable = true;
      efi = {
        canTouchEfiVariables = true;
        efiSysMountPoint = "/boot/efi";
      };
    };
    kernelModules = [
      "kvm-amd"
      "vhost_vsock"
    ];
    extraModulePackages = [ ];
    extraModprobeConfig = "options kvm_amd nested=1";
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/89692dd1-778a-4ba7-860f-766318c1699e";
      fsType = "ext4";
    };
    "/boot/efi" = {
      device = "/dev/disk/by-uuid/3676-427E";
      fsType = "vfat";
    };
    "/var/lib/lxd/shmounts" = {
      device = "tmpfs";
      fsType = "tmpfs";
    };
    "/var/lib/lxd/devlxd" = {
      device = "tmpfs";
      fsType = "tmpfs";
    };
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/7ef63cd2-cac6-4a64-aa29-9e8f2afd4887"; }
  ];

  networking = {
    useDHCP = lib.mkDefault true;
    hostId = "d4b231f1";
    hostName = "juniper"; 
  };

  hardware = {
    cpu = {
      amd = {
        updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      };
    };
    video = {
      hidpi = {
        enable = lib.mkDefault true;
      };
    };
  };
}
