# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    "${builtins.fetchGit { url = "https://github.com/kekrby/nixos-hardware.git"; }}/apple/t2"
  ];

  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };

    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [
        "kvm-intel"
       # "wl"
      ];
    };  
    kernelModules = [
     # "wl"
    ];
    extraModulePackages = [
     # config.boot.kernelPackages.broadcom_sta
    ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/30775c74-d6fe-4308-93bf-67cecc73371a";
      fsType = "btrfs";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/5F66-17ED";
      fsType = "vfat";
    };
  };
  
  swapDevices = [ ];

  networking = {
    useDHCP = lib.mkDefault true;

    hostId = "007f0200";
    hostName = "pine";
 
    networkmanager.enable = true;
    
    interfaces = {
      enp2s0f1u1.useDHCP = lib.mkDefault true;
      wlp3s0.useDHCP = lib.mkDefault true;
    };
  };
  
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware = {
    cpu = {
      intel = {
        updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      };
    };
    video = {
      hidpi = {
        enable = lib.mkDefault true;
      };
    };
  };
}
